FROM tryton/tryton:office
ENV DB_HOSTNAME="" 
ENV DB_USER="" 
ENV DB_PASSWORD="" 
# postgresql://DB_USER:DB_PASSWORD@DB_HOSTNAME:5432/
ENV TRYTOND_DATABASE_URI="postgresql://DB_USER:DB_PASSWORD@DB_HOSTNAME:5432/"
ENV TRYTOND_ATTACHMENT_FILESTORE=True
RUN pip install m9s-account-de